name: 'auto-label-flutter'
description: 'For flutter repos, automatically label issues and pull requests'
author: 'CaiJingLong'
inputs:
  github-token:
    description: 'The GitHub token to use for the action'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
